---
- hosts: localhost
  connection: local
  become: true

  pre_tasks:
      - include_tasks: tasks/pre_tasks.yml

  tasks:
      - include_tasks: tasks/install_packages.yml
      - include_tasks: tasks/setup_fish.yml
      - include_tasks: tasks/configure_user.yml
      - include_tasks: tasks/setup_ssh.yml
      - include_tasks: tasks/install_docker.yml
