- name: Download get-docker.sh script
  get_url:
    url: https://get.docker.com/
    dest: /tmp/get-docker.sh
    mode: "u+x"
    validate_certs: no

- name: Execute get-docker.sh script
  command: /tmp/get-docker.sh

- name: Enable Docker service
  systemd:
    name: docker
    enabled: yes
    state: started

- name: Add user {{ env.USER }} to the docker group
  shell: sudo usermod -aG docker {{ env.USER }}
