- name: Load Environment Variables
  ansible.builtin.include_vars:
    file: env_local
    name: env

- name: Set time zone to {{env.TZ}}
  ansible.builtin.timezone:
    name: "{{env.TZ}}"

- name: Update packages
  package:
    update_cache: yes
    state: latest
    autoremove: yes
    name: "*"
  changed_when: false
