- name: Check if .ssh directory exists
  stat:
    path: /home/{{ env.USER }}/.ssh
  register: ssh_dir

- name: Create .ssh directory
  file:
    path: /home/{{ env.USER }}/.ssh
    state: directory
    owner: "{{ env.USER }}"
  when: not ssh_dir.stat.exists

- name: Generate SSH keypair
  openssh_keypair:
    path: /home/{{ env.USER }}/.ssh/id_rsa
    type: rsa
    size: 4096
    state: present

- name: Fix owner of the generated pub key
  file:
    path: /home/{{ env.USER }}/.ssh/id_rsa.pub
    owner: "{{ env.USER }}"
    group: "{{ env.USER }}"

- name: Fix owner of the generated private key
  file:
    path: /home/{{ env.USER }}/.ssh/id_rsa
    owner: "{{ env.USER }}"
    group: "{{ env.USER }}"
